name: Ubuntu

on:
  workflow_call:
    inputs:
      is_nightly:
        description: 'Is nightly CI run'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  packages: read

jobs:
  gcc-build-codecov:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
      issues: write
      pull-requests: write
    container:
      image: ghcr.io/learning-process/ppc-ubuntu:1.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-gcc
          create-symlink: true
          max-size: 1G
      - name: CMake configure
        run: >
          cmake -S . -B build -G Ninja
          -D CMAKE_BUILD_TYPE=RELEASE
          -D CMAKE_VERBOSE_MAKEFILE=ON -D USE_COVERAGE=ON
          -DCMAKE_INSTALL_PREFIX=install
      - name: Build project
        run: |
          cmake --build build --parallel -- --quiet
      - name: Install project
        run: |
          cmake --build build --target install -- --quiet
      - name: Run tests (MPI)
        run: scripts/run_tests.py --running-type="processes" --additional-mpi-args="--oversubscribe"
        env:
          PPC_NUM_PROC: 2
          PPC_NUM_THREADS: 2
          OMPI_ALLOW_RUN_AS_ROOT: 1
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      - name: Run tests (threads)
        run: scripts/run_tests.py --running-type="threads" --counts 1 2 3 4
        env:
          PPC_NUM_PROC: 1
      - name: Generate gcovr Coverage Data
        run: |
          mkdir cov-report
          cd build
          gcovr --gcov-executable `which gcov-14` \
                -r ../ \
                --exclude '.*3rdparty/.*' \
                --exclude '/usr/.*' \
                --exclude '.*tasks/.*/tests/.*' \
                --exclude '.*modules/.*/tests/.*' \
                --exclude '.*tasks/common/runners/.*' \
                --exclude '.*modules/runners/.*' \
                --exclude '.*modules/util/include/perf_test_util.hpp' \
                --exclude '.*modules/util/include/func_test_util.hpp' \
                --exclude '.*modules/util/src/func_test_util.cpp' \
                --xml --output ../coverage.xml \
                --html=../cov-report/index.html --html-details
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.5.2
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage report artifact
        id: upload-cov
        uses: actions/upload-artifact@v6
        with:
          name: cov-report
          path: 'cov-report'
      - name: Comment coverage report link
        # TODO: Support PRs from forks and handle cases with insufficient write permissions
        continue-on-error: true
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Coverage report is available for download
            [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
      - name: Show ccache stats
        run: ccache --show-stats
